baseURL = "https://guoda.savolro.com/"
languageCode = "en-us"
title = "Guoda Orlovaite | Portfolio"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "#about"
weight  = 2
[[menu.main]]
name    = "Resume"
url     = "#feature"
weight  = 3
[[menu.main]]
name    = "Portfolio"
url     = "#works"
weight  = 4
#[[menu.main]]
#name    = "Vectors"
#url     = "#works2"
#weight  = 5
[[menu.main]]
name    = "Contact"
url     = "#call-to-action"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Portfolio"
author = "sloira"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.mp4"
heading = "GUODA ORLOVAITE"
description = "The one that's hella awkward at any given situation"

# Homepage About Section
[params.about]
enable  = true
content = "Almost as any kid out there, I enjoyed doodling on the walls. While growing up, I slowly realized that art defines my world, so I continued drawing.<br><br>Currently, I am doing my best to achieve my goal - getting a position where I could create art and learn from the best.<br><br>Improving is one of my biggest objectives. Not only in mastering digital art, but traditional art and graphic design too. I constantly seek to become a better version of myself.<br><br>I am keen on learning various digital techniques, and I strive to master them. Thanks to the opportunity I‘ve got at my current workplace, I‘ve started learning Illustrator in the year 2020. Now, most of my time at work I spend making vector elements for various projects.<br><br>I am flexible and curious person, therefore, if I set my mind to it – I accomplish it."
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "Telepathy is one of my weaker skills, so please use my gmail instead!"
content = "guodaorlovaite@gmail.com"


# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Portfolio"

# Practise Section On Homepage
[params.portfolio2]
enable  = false
title   = "Vectors"


# social icon
[[params.socialIcon]]
icon = "ion-social-instagram"
url = "https://www.instagram.com/pengupun/"
