name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          name: id_rsa # optional

    - name: Fetch submodules
      shell: bash
      run: | 
          git submodule add -b master git@github.com:Gruodyte/Gruodyte.github.io.git public -f

    - name: Install Hugo
      run: sudo snap install hugo
    - name: Build site
      run: hugo

    - name: Publish site
      run: |
        cd public

        git config user.email "borlovas@gmail.com"
        git config user.name "Savolro"

        git add .
        msg="rebuilding site $(date)"
        git commit -m "$msg" || true # ignore error if nothing was changed
        git push origin HEAD:master

